### ISSUE TITLE
I believe no_std is broken

### ISSUE THREAD

**Issue by boehs** [NicolasKlenert/enterpolation#23]
`Cargo.toml` shows

```toml
num-traits = "0.2"
```

, but this is problematic as [std is a default feature](https://docs.rs/crate/num-traits/latest/features)

Instead it should be 

```toml
num-traits = {version = "0.2", default-features = false}
```

... I think at least :)

- Edit 0: Same thing for `assert_float_eq`
- Edit 1: And the topology
- Edit 2: topology also has this issue in their crate
- https://github.com/boehs/enterpolation/tree/patch-1 https://github.com/boehs/topology-traits/tree/patch-1

**Comment by ede1998** [comment]
Had the same issue:
```
`std` is required by `assert_float_eq` because it does not declare `#![no_std]`
```

Cargo.toml:
```toml
# ...
[dependencies]
enterpolation = { version = "0.2.0", default-features = false, features = ["linear", "libm"] }
```
